# FROM public.ecr.aws/lambda/python:3.9 as build

# RUN yum install -y unzip && \
#     curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_linux64.zip" && \
#     curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1058922%2Fchrome-linux.zip?alt=media" && \
#     unzip /tmp/chromedriver.zip -d /opt/ && \
#     unzip /tmp/chrome-linux.zip -d /opt/

# FROM public.ecr.aws/lambda/python:3.9
# RUN yum install atk cups-libs gtk3 libXcomposite alsa-lib \
#     libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
#     libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
#     xorg-x11-xauth dbus-glib dbus-glib-devel -y



# # Install the function's dependencies using file requirements.txt
# # from your project folder.

# COPY requirements.txt  .
# RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"


# # Copy function code and chrome   
# COPY main_app.py ${LAMBDA_TASK_ROOT}
# COPY --from=build /opt/chrome-linux /opt/chrome
# COPY --from=build /opt/chromedriver /opt/
# # Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
# CMD [ "main_app.handler" ]



# Use the official Python image as the parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /src

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install Google Chrome and ChromeDriver
# RUN apt-get update && apt-get install -y wget gnupg2 && \
#     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
#     dpkg -i google-chrome-stable_current_amd64.deb && \
#     rm google-chrome-stable_current_amd64.deb && \
#     wget https://chromedriver.storage.googleapis.com/93.0.4577.63/chromedriver_linux64.zip && \
#     unzip chromedriver_linux64.zip && \
#     mv chromedriver /usr/bin && \
#     rm chromedriver_linux64.zip

RUN yum install -y unzip && \
    curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_linux64.zip" && \
    curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1058922%2Fchrome-linux.zip?alt=media" && \
    unzip /tmp/chromedriver.zip -d /opt/ && \
    unzip /tmp/chrome-linux.zip -d /opt/

# Run the command to start the server

CMD ["uvicorn", "main_app:app", "--host", "0.0.0.0", "--port", "80"]